name = "ESDLPaperCode"
uuid = "2502ad13-e485-5df4-bc88-d00dc12670bb"

[deps]
AWSCore = "4f1ea46c-232b-54a6-9b17-cc2d0f3e6598"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ESDL = "359177bc-a543-11e8-11b7-bb015dba3358"
ESDLPlots = "d555b242-3f29-57aa-84ea-3df92a135dfd"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Zarr = "0a941bbe-ad1d-11e8-39d9-ab76183a1d99"
